spring.application.name=products
server.port=8086
spring.kafka.producer.bootstrap-servers=localhost:9092,localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Base path
server.servlet.context-path=/productMS/api

# SpringDoc settings
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.paths-to-match=/v1/products/**

# Kafka Topic Configuration
kafka.topic.product-created.name=product-created-events-topic
kafka.topic.product-created.partitions=3
kafka.topic.product-created.replicas=3
kafka.topic.product-created.min-insync-replicas=2